import { Component, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { LanguageService } from '../../services/language.service';
import * as i0 from "@angular/core";
export class Footer {
    route = inject(ActivatedRoute);
    languageService = inject(LanguageService);
    lang = this.languageService.getLangFromRoute(this.route);
    static ɵfac = function Footer_Factory(__ngFactoryType__) { return new (__ngFactoryType__ || Footer)(); };
    static ɵcmp = /*@__PURE__*/ i0.ɵɵdefineComponent({ type: Footer, selectors: [["app-footer"]], decls: 66, vars: 8, consts: [[1, "footer"], [1, "footer-container"], [1, "footer-col"], [1, "footer-heading"], [1, "footer-list"], ["href", "#home"], ["href", "#menu"], ["href", "#contact"], ["href", "tel:+4751668082"], ["href", "mailto:shahi.mahal2026@hotmail.com"], [1, "footer-address"], [1, "social-icons"], ["href", "https://www.facebook.com/people/Shaahi-Mahall-Indisk-Restaurant/61576510912597/", "target", "_blank", 1, "social-icon"], ["viewBox", "0 0 24 24", "fill", "none", "stroke", "currentColor", "stroke-width", "2", "stroke-linecap", "round", "stroke-linejoin", "round"], ["d", "M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"], ["href", "https://www.instagram.com/shaahi.mahall/", "target", "_blank", 1, "social-icon"], ["x", "2", "y", "2", "width", "20", "height", "20", "rx", "5", "ry", "5"], ["d", "M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"], ["x1", "17.5", "y1", "6.5", "x2", "17.51", "y2", "6.5"], [1, "footer-col", 2, "flex", "0.8"], ["href", "https://www.foodsted.no/webmail", "target", "_blank"], [1, "footer-col", 2, "flex", "1.5"], [1, "app-downloads"], [1, "app-column"], ["href", "https://play.google.com/store/apps/details?id=com.foodsted.apps", "target", "_blank"], ["src", "./images/playStore.png", "alt", "Google Play", 1, "app-badge"], ["src", "./images/playstoreQr.png", "alt", "Google Play QR Code", 1, "app-qr"], ["href", "https://apps.apple.com/us/app/foodsted/id1530698059", "target", "_blank"], ["src", "./images/appStore.png", "alt", "App Store", 1, "app-badge"], ["src", "./images/appstoreQr.png", "alt", "App Store QR Code", 1, "app-qr"], [1, "footer-bottom-wrapper"], [1, "footer-bottom"], [1, "copyright"], [1, "powered-by"], ["src", "./images/foodstedicon.png", "alt", "FoodSted Logo"], ["id", "moveTopBtn", "title", "Go to top"]], template: function Footer_Template(rf, ctx) { if (rf & 1) {
            i0.ɵɵdomElementStart(0, "footer", 0)(1, "div", 1)(2, "div", 2)(3, "h4", 3);
            i0.ɵɵtext(4);
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(5, "ul", 4)(6, "li")(7, "a", 5);
            i0.ɵɵtext(8);
            i0.ɵɵdomElementEnd()();
            i0.ɵɵdomElementStart(9, "li")(10, "a", 6);
            i0.ɵɵtext(11);
            i0.ɵɵdomElementEnd()();
            i0.ɵɵdomElementStart(12, "li")(13, "a", 7);
            i0.ɵɵtext(14);
            i0.ɵɵdomElementEnd()()()();
            i0.ɵɵdomElementStart(15, "div", 2)(16, "h4", 3);
            i0.ɵɵtext(17);
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(18, "ul", 4)(19, "li")(20, "a", 8);
            i0.ɵɵtext(21, "+47 51 66 80 82");
            i0.ɵɵdomElementEnd()();
            i0.ɵɵdomElementStart(22, "li")(23, "a", 9);
            i0.ɵɵtext(24, "shahi.mahal2026@hotmail.com");
            i0.ɵɵdomElementEnd()();
            i0.ɵɵdomElementStart(25, "li")(26, "p", 10);
            i0.ɵɵtext(27, "Mauritz Kartevoldsplass 1");
            i0.ɵɵdomElement(28, "br");
            i0.ɵɵtext(29, "4306 ,Sandnes");
            i0.ɵɵdomElementEnd()()();
            i0.ɵɵdomElementStart(30, "div", 11)(31, "a", 12);
            i0.ɵɵnamespaceSVG();
            i0.ɵɵdomElementStart(32, "svg", 13);
            i0.ɵɵdomElement(33, "path", 14);
            i0.ɵɵdomElementEnd()();
            i0.ɵɵnamespaceHTML();
            i0.ɵɵdomElementStart(34, "a", 15);
            i0.ɵɵnamespaceSVG();
            i0.ɵɵdomElementStart(35, "svg", 13);
            i0.ɵɵdomElement(36, "rect", 16)(37, "path", 17)(38, "line", 18);
            i0.ɵɵdomElementEnd()()()();
            i0.ɵɵnamespaceHTML();
            i0.ɵɵdomElementStart(39, "div", 19)(40, "ul", 4)(41, "li")(42, "a", 20);
            i0.ɵɵtext(43, "Webmail");
            i0.ɵɵdomElementEnd()()()();
            i0.ɵɵdomElementStart(44, "div", 21)(45, "h4", 3);
            i0.ɵɵtext(46);
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(47, "div", 22)(48, "div", 23)(49, "a", 24);
            i0.ɵɵdomElement(50, "img", 25);
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElement(51, "img", 26);
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(52, "div", 23)(53, "a", 27);
            i0.ɵɵdomElement(54, "img", 28);
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElement(55, "img", 29);
            i0.ɵɵdomElementEnd()()()();
            i0.ɵɵdomElementStart(56, "div", 30)(57, "div", 31)(58, "div", 32);
            i0.ɵɵtext(59);
            i0.ɵɵdomElementEnd();
            i0.ɵɵdomElementStart(60, "div", 33);
            i0.ɵɵdomElement(61, "img", 34);
            i0.ɵɵdomElementStart(62, "span");
            i0.ɵɵtext(63);
            i0.ɵɵdomElementEnd()()();
            i0.ɵɵdomElementStart(64, "button", 35);
            i0.ɵɵtext(65, "\u2191");
            i0.ɵɵdomElementEnd()()();
        } if (rf & 2) {
            i0.ɵɵadvance(4);
            i0.ɵɵtextInterpolate(ctx.languageService.t(ctx.lang, "quickinfo"));
            i0.ɵɵadvance(4);
            i0.ɵɵtextInterpolate(ctx.languageService.t(ctx.lang, "home"));
            i0.ɵɵadvance(3);
            i0.ɵɵtextInterpolate(ctx.languageService.t(ctx.lang, "menu"));
            i0.ɵɵadvance(3);
            i0.ɵɵtextInterpolate(ctx.languageService.t(ctx.lang, "contactus"));
            i0.ɵɵadvance(3);
            i0.ɵɵtextInterpolate(ctx.languageService.t(ctx.lang, "information"));
            i0.ɵɵadvance(29);
            i0.ɵɵtextInterpolate(ctx.languageService.t(ctx.lang, "app"));
            i0.ɵɵadvance(13);
            i0.ɵɵtextInterpolate1(" ", ctx.languageService.t(ctx.lang, "allrightrevserved"), " ");
            i0.ɵɵadvance(4);
            i0.ɵɵtextInterpolate(ctx.languageService.t(ctx.lang, "poweredby"));
        } }, encapsulation: 2 });
}
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassMetadata(Footer, [{
        type: Component,
        args: [{ selector: 'app-footer', imports: [], template: "    <footer class=\"footer\">\n        <div class=\"footer-container\">\n            <div class=\"footer-col\">\n                <h4 class=\"footer-heading\">{{ languageService.t(lang, 'quickinfo') }}</h4>\n                <ul class=\"footer-list\">\n                    <li><a href=\"#home\">{{ languageService.t(lang, 'home') }}</a></li>\n                    <li><a href=\"#menu\">{{ languageService.t(lang, 'menu') }}</a></li>\n                    <li><a href=\"#contact\">{{ languageService.t(lang, 'contactus') }}</a></li>\n                </ul>\n            </div>\n            <div class=\"footer-col\">\n                <h4 class=\"footer-heading\">{{ languageService.t(lang, 'information') }}</h4>\n                <ul class=\"footer-list\">\n                    <li><a href=\"tel:+4751668082\">+47 51 66 80 82</a></li>\n                    <li><a href=\"mailto:shahi.mahal2026@hotmail.com\">shahi.mahal2026@hotmail.com</a></li>\n                    <li>\n                        <p class=\"footer-address\">Mauritz Kartevoldsplass 1<br>4306 ,Sandnes</p>\n                    </li>\n                </ul>\n                <div class=\"social-icons\">\n                    <a href=\"https://www.facebook.com/people/Shaahi-Mahall-Indisk-Restaurant/61576510912597/\" target=\"_blank\" class=\"social-icon\">\n                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"\n                            stroke-linecap=\"round\" stroke-linejoin=\"round\">\n                            <path d=\"M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z\"></path>\n                        </svg>\n                    </a>\n                    <a href=\"https://www.instagram.com/shaahi.mahall/\" target=\"_blank\" class=\"social-icon\">\n                        <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"\n                            stroke-linecap=\"round\" stroke-linejoin=\"round\">\n                            <rect x=\"2\" y=\"2\" width=\"20\" height=\"20\" rx=\"5\" ry=\"5\"></rect>\n                            <path d=\"M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z\"></path>\n                            <line x1=\"17.5\" y1=\"6.5\" x2=\"17.51\" y2=\"6.5\"></line>\n                        </svg>\n                    </a>\n                </div>\n            </div>\n            <div class=\"footer-col\" style=\"flex: 0.8;\">\n                <ul class=\"footer-list\">\n                    <li><a href=\"https://www.foodsted.no/webmail\" target=\"_blank\">Webmail</a></li>\n                </ul>\n            </div>\n            <div class=\"footer-col\" style=\"flex: 1.5;\">\n                <h4 class=\"footer-heading\">{{ languageService.t(lang, 'app') }}</h4>\n                <div class=\"app-downloads\">\n                    <div class=\"app-column\">\n                        <a href=\"https://play.google.com/store/apps/details?id=com.foodsted.apps\" target=\"_blank\"><img src=\"./images/playStore.png\" alt=\"Google Play\" class=\"app-badge\"> </a>\n                        <img src=\"./images/playstoreQr.png\" alt=\"Google Play QR Code\" class=\"app-qr\">\n                    </div>\n                    <div class=\"app-column\">\n                        <a href=\"https://apps.apple.com/us/app/foodsted/id1530698059\" target=\"_blank\"><img src=\"./images/appStore.png\" alt=\"App Store\" class=\"app-badge\"></a>\n                        <img src=\"./images/appstoreQr.png\" alt=\"App Store QR Code\" class=\"app-qr\">\n                    </div>\n                </div>\n            </div>\n        </div>\n        <div class=\"footer-bottom-wrapper\">\n            <div class=\"footer-bottom\">\n                <div class=\"copyright\">\n                    {{ languageService.t(lang, 'allrightrevserved') }}\n                </div>\n                <div class=\"powered-by\">\n                    <img src=\"./images/foodstedicon.png\" alt=\"FoodSted Logo\">\n                    <span>{{ languageService.t(lang, 'poweredby') }}</span>\n                </div>\n            </div>\n    \n    <button id=\"moveTopBtn\" title=\"Go to top\">\u2191</button>\n        </div>\n    </footer>" }]
    }], null, null); })();
(() => { (typeof ngDevMode === "undefined" || ngDevMode) && i0.ɵsetClassDebugInfo(Footer, { className: "Footer", filePath: "app/components/footer/footer.ts", lineNumber: 11 }); })();
